plugin:
    name: 'Fortify Smart IP Blocker'
    description: 'wobqqq.fortify::lang.messages.fortify_description'
    author: wobqqq
    icon: icon-shield
    homepage: 'https://github.com/wobqqq/oc-fortify-plugin'
